name: meditation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  get: 4.3.8
  hexcolor: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
